apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNVEV5TVRVdwpPVE14TXpGYUZ3MDBNVEV5TVRVd09UTXhNekZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFESlVTaXlaekdIbXBGa2hUVEJWNTdlS2s3Rk12am04MFZ5QlFSNUlrcnpLRnFhYnJ1TApiN08zUENjZ0JJRG8rTVdZbEtWM0haWXMvakFUTnNvS3JKWG5nWjR3cEZCQUd6NVZhSnJXUHZNVVpGWmZNOGtGCkhjRkNmZHNpU3ZDMHVzdHUxUlAzTEhEWGN2b1R4Y1pnSDlXUlgrcHdiYjRtelpVRWFJNFZja3hDTWlNU0NxaVIKb2pDbXh3eGdwNW9qNWlNUU1zZTVML2h6bFc1Tm9YRHlkUnVkWVBudWtRTU1YYXBna1BQbXZVNXJzNm5UcXF3MQpOZWNjdHA1d2pad2pMb2o5TllnWVJ4bjZIOHVLbVg1WGFQdmVMaUxyZjRyYXJhdHNiVkRPTy9lbjF2THNzNC9lCmNCSVpHV3NsalRnTnZBUnhobXoxTzg4NTFveFdDdVhDV2xZekFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlM5d0Z4UUFHZ0twZW5Pbzc1NQp0Q3dKZHQwTTFEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFOd29xVGc0eEFjcnZ4Uk01ZjRCbHJuRVZmcVVxCk8yTWx4MUZjZzV1MHEwU0FpdkFWN0J6K09UcHgrNmFwN2I3Y0xYaitYWFE3bHN2T01UaTh1V2d2c0hXUzNkQ00KaUVaR29SZE12YUZMMHhCNVR4Vk1WeWwvbU41TFZVanVUMmFmVC96dVZFWk1WTytyeGtSa0NQYW93MjFkanZYMgpZVkFsejVuSktwMGhIMEp0QjBXdk45dkF6WkMyOG5Vay9sdFo3OHM0ODFKUG55U2hkMjJtSXRzRFo3TGtocGl2Ckd4dXFHaEZsZ3pTQjlqb0xPNk1CdUNKUStpR0R1TkVGcW16bG95OVZjK0ErWGg1WkNMSStxa0JUVk9EQ0hiMzgKMkdkaUV5R0NYM0RoTk1KYjVYaFBobXUrUFJ2ZEhJcHhPVHd2OENHdCtIUjZGUjlMWDFXVTExQlhxZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://f5c5965a-13aa-4b13-9134-d4a0b31b3fee.k8s.ondigitalocean.com
  name: do-ams3-k8s-kasteel
contexts:
- context:
    cluster: do-ams3-k8s-kasteel
    user: do-ams3-k8s-kasteel-admin
  name: do-ams3-k8s-kasteel
current-context: do-ams3-k8s-kasteel
kind: Config
preferences: {}
users:
- name: do-ams3-k8s-kasteel-admin
  user:
    token: 96a6c13206bafddfdbed75d0444187b401adddc1711a813af954b219fe37417e
